<a href="https://colab.research.google.com/github/oishiki/oishiki/blob/main/CB10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
revenue = np.array([[100,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [2]:
profit = revenue - expenses
profit

array([[ 20, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [3]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [5]:
np.dot(price_per_unit, units)

array([34400, 50000, 64400])

EXERCISE 


1

In [6]:
revenue_new = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])

In [7]:
revenue_new

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [10]:
revenue_rupees = 75*revenue_new
revenue_rupees

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

2

In [11]:
price_per_unit_new = np.array([20,30,15])

In [12]:
units_new = np.array([[50,60,25],[10,13,5],[40,70,52]])

In [13]:
np.dot(price_per_unit_new, units_new)

array([1900, 2640, 1430])